---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: collect a list of the datacenters
    vmware.vmware_rest.vcenter_datacenter_info:
      vcenter_hostname: vcenter.ccu.loc
      vcenter_username: "{{ ansible_user }}"
      vcenter_password: "{{ ansible_password }}"
      vcenter_validate_certs: false
    register: search_results
  - name: show registered output
    ansible.builtin.debug:
      var: search_results
