---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: Build a list of all the folders
    vmware.vmware_rest.vcenter_folder_info:
      vcenter_hostname: vcenter.fqdn
      vcenter_username: "{{ ansible_user }}"
      vcenter_password: "{{ ansible_password }}"
      vcenter_validate_certs: false
    register: search_results
  - name: show registered output
    ansible.builtin.debug:
      var: search_results
