---
- hosts: all
  gather_facts: no
  tasks:
  - name: load an acl into the device
    eos_config:
      lines:
        - 10 permit ip host 192.0.2.1 any log
        - 20 permit ip host 192.0.2.2 any log
        - 30 permit ip host 192.0.2.3 any log
        - 40 permit ip host 192.0.2.4 any log
      parents: ip access-list standard
      before: no ip access-list standard
      replace: block
