---
- hosts: all
  gather_facts: no
  vars:
    provider:
      password: "{{ ansible_password }}" # in group_vars/f5.yml or use -k flag to prompt for pass
      server: "{{ inventory_hostname }}"
      #server: "34.105.17.221"
      user: "{{ ansible_user }}"
      validate_certs: no
      server_port: 8443
  collections:
    - f5networks.f5_module
  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost
    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: 80
      with_items:
        - host: 10.10.10.10
          name: web01
        - host: 10.10.10.20
          name: web02
      delegate_to: localhost
