all:
  children:
    datacenter1:
      hosts:
        cisco-ios-1:
          ansible_host: 34.105.33.224
        junos-1:
          ansible_host: 35.197.36.6
        spiderlounge.org:
    datacenter2:
      hosts:
        cisco-ios-2:
          ansible_host: 35.197.36.60
        junos-2:
          ansible_host: 35.197.36.6
    ios:
      hosts:
        cisco-ios-1: {}
        cisco-ios-2: {}
    junos:
      hosts:
        junos-1: {}
    linux:
      hosts:
        spiderlounge.org: {}
    ungrouped: {}
