---
- hosts: all
  gather_facts: no
  tasks:
  - name: Enable NETCONF
    connection: network_cli
    junos_netconf:
      listens_on: 830
      state: present
    when: ansible_network_os == 'junos'
...
