---
- hosts: all
  gather_facts: no
  tasks:
  - name: Backup current switch config (junos)
    junos_config:
      backup: yes
    register: backup_junos_location
    when: ansible_network_os == 'junos'
  - debug: var=backup_junos_location

