---
- hosts: all
  gather_facts: yes
  gather_subset: min
  serial: 20
  tasks:
    - name: linux hostname
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
      command: hostname
    #  register: linux_hostname
    #- debug: var=linux_hostname
    - name: windows hostname
      when: ansible_os_family == "Windows"
      win_command: hostname
    #  register: win_hostname
    #- debug: var=win_hostname
