---
- hosts: all
  vars:
    cid: <PUT_CID_HERE>
    deb_pkg: <NAME_OF_DEB_PACKAGE_HERE_PUT_FILE_IN_files_dir>
    rpm_pkg: <NAME_OF_RPM_PACKAGE_HERE_PUT_FILE_IN_file_dir>
    # Windows packages is always called WindowsSensor.exe
    win_pkg: WindowsSensor.exe
  serial: 20
  tasks:
    - name: scp deb package
      copy:
        src: ./{{ deb_pkg }}
        dest: /tmp/
        owner: root
        group: root
        mode: '0644'
      become: true
      become_user: root
      when: ansible_os_family == "Debian"
    - name: Install a .deb package
      apt:
        deb: /tmp/{{ deb_pkg }}
      become: true
      become_user: root
      when: ansible_os_family == "Debian"
    - name: scp rpm package
      copy:
        src: ./{{ rpm_pkg }}
        dest: /tmp/
        owner: root
        group: root
        mode: '0644'
      become: true
      become_user: root
      when: ansible_os_family == "RedHat"
    - name: install rpm package
      yum:
        name: /tmp/{{ rpm_pkg }}
      become: true
      become_user: root
      when: ansible_os_family == "RedHat"
    - name: license linux
      command: /opt/CrowdStrike/falconctl -s --cid={{ cid }}
      become: true
      become_user: root
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
      args:
        creates: /opt/CrowdStrike/Registry.bin
    - name: enable falcon-sensor.service systemd way on {{ inventory_hostname }}
      systemd:
        state: started
        name: falcon-sensor
        enabled: yes
        masked: no
        daemon_reload: yes
      become: true
      become_user: root
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
    - name: scp package
      win_copy:
        src: ./{{ win_pkg }}
        dest: C:\Windows\temp\
        owner: root
        group: root
      when: ansible_os_family == "Windows"
    - name: Install Falcon Sensor
      win_command: C:\Windows\temp\WindowsSensor.exe /install /quiet /norestart CID={{ cid }}
      when: ansible_os_family == "Windows"
