---
- hosts: all
  gather_facts: no
  tasks:
  - name: set eos ntp server
    eos_config:
      lines: ntp server {{ ntp_host }}
    when: ansible_network_os == 'eos'
  - name: set ios ntp server
    ios_config:
      lines: ntp server {{ ntp_host }}
    when: ansible_network_os == 'ios'
  - name: set junos ntp server
    junos_command:
      commands:
        - config
        - set system ntp server {{ ntp_host }}
        - commit
    when: ansible_network_os == 'junos'
...
