---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: Gather Information About All Clusters In a Datacenter
    vmware.vmware.cluster_info:
      hostname: "vcenter.ccu.loc"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      datacenter_name: datacenter-21
    register: search_results
  - name: show registered output
    ansible.builtin.debug:
      var: search_results
