---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
  - name: Gather guest vm info
    vmware.vmware.guest_info:
      hostname: "vcenter.fqdn"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      guest_name: "name of guest"
    register: search_results
  - name: show registered output
    ansible.builtin.debug:
      var: search_results
